version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "docker"
    directories:
      - "/images/analysis"
      - "/images/base"
      - "/images/deploy"
      - "/images/dotnet"
      - "/images/java"
      - "/images/node"
      - "/images/python"
      - "/images/rust"
      - "/images/scanner"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build"
    labels:
      - "dependencies"
      - "docker"
