#!/usr/bin/env bash
# generate-bake.sh - Generate docker-bake.hcl from versions.json
#
# Reads the stack/version matrix and produces a BuildKit bake file
# with one target per (stack, version) pair, plus a default group.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSIONS_FILE="${ROOT_DIR}/versions.json"
OUTPUT_FILE="${ROOT_DIR}/docker-bake.hcl"

if [[ ! -f "$VERSIONS_FILE" ]]; then
    echo "ERROR: versions.json not found at ${VERSIONS_FILE}" >&2
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required but not found" >&2
    exit 1
fi

# Read global values
REGISTRY="$(jq -r '.registry' "$VERSIONS_FILE")"
YQ_VERSION="$(jq -r '.tools.yq' "$VERSIONS_FILE")"
JQ_VERSION="$(jq -r '.tools.jq' "$VERSIONS_FILE")"
JV_VERSION="$(jq -r '.tools.jv' "$VERSIONS_FILE")"

# Read deploy_tools versions (used by deploy image)
declare -A DEPLOY_TOOLS
while IFS='=' read -r key value; do
    DEPLOY_TOOLS["$key"]="$value"
done < <(jq -r '.deploy_tools | to_entries[] | "\(.key)=\(.value)"' "$VERSIONS_FILE")

# Read security_tools versions (used by quality and security images)
declare -A SECURITY_TOOLS
while IFS='=' read -r key value; do
    SECURITY_TOOLS["$key"]="$value"
done < <(jq -r '.security_tools | to_entries[] | "\(.key)=\(.value)"' "$VERSIONS_FILE")

# Collect all target names for the default group
ALL_TARGETS=()

# Start generating
{
    cat <<'HEADER'
// Auto-generated by scripts/generate-bake.sh -- do not edit manually.
// Regenerate with: ./scripts/generate-bake.sh

HEADER

    printf 'variable "REGISTRY" { default = "%s" }\n' "$REGISTRY"
    printf 'variable "SHA" { default = "" }\n'
    echo ""

    # Iterate over stacks
    for stack in $(jq -r '.stacks | keys[]' "$VERSIONS_FILE"); do
        versions="$(jq -r ".stacks.\"${stack}\".versions[]" "$VERSIONS_FILE")"

        for version in $versions; do
            # Target name: stack-version (dots replaced with dashes for HCL)
            target_name="${stack}-$(echo "$version" | tr '.' '-')"
            ALL_TARGETS+=("\"${target_name}\"")

            # Image name
            image_name="brik-runner-${stack}"

            # Determine latest tag: first version in the array gets "latest"
            first_version="$(jq -r ".stacks.\"${stack}\".versions[0]" "$VERSIONS_FILE")"
            is_latest="false"
            [[ "$version" == "$first_version" ]] && is_latest="true"

            # Build tags
            tags="["
            tags+="\"${REGISTRY}/${image_name}:${version}\","
            if [[ "$is_latest" == "true" ]]; then
                tags+="\"${REGISTRY}/${image_name}:latest\","
            fi
            tags+="]"

            # Build args block - base args for all stacks
            extra_args=""
            if [[ "$stack" == "analysis" ]]; then
                extra_args=$(cat <<XARGS
    SEMGREP_VERSION         = "${SECURITY_TOOLS[semgrep]}"
    CHECKOV_VERSION         = "${SECURITY_TOOLS[checkov]}"
    LICENSE_FINDER_VERSION  = "${SECURITY_TOOLS[license_finder]}"
    SCANCODE_VERSION        = "${SECURITY_TOOLS[scancode_toolkit]}"
XARGS
)
            elif [[ "$stack" == "scanner" ]]; then
                extra_args=$(cat <<XARGS
    GRYPE_VERSION           = "${SECURITY_TOOLS[grype]}"
    SYFT_VERSION            = "${SECURITY_TOOLS[syft]}"
    OSV_SCANNER_VERSION     = "${SECURITY_TOOLS[osv_scanner]}"
    HADOLINT_VERSION        = "${SECURITY_TOOLS[hadolint]}"
    GITLEAKS_VERSION        = "${SECURITY_TOOLS[gitleaks]}"
    TRUFFLEHOG_VERSION      = "${SECURITY_TOOLS[trufflehog]}"
    DOCKLE_VERSION          = "${SECURITY_TOOLS[dockle]}"
XARGS
)
            elif [[ "$stack" == "deploy" ]]; then
                extra_args=$(cat <<XARGS
    HELM_VERSION            = "${DEPLOY_TOOLS[helm]}"
    KUBECTL_VERSION         = "${DEPLOY_TOOLS[kubectl]}"
    ARGOCD_VERSION          = "${DEPLOY_TOOLS[argocd]}"
XARGS
)
            fi

            # Format extra_args: add leading newline only if non-empty
            formatted_extra=""
            if [[ -n "$extra_args" ]]; then
                formatted_extra=$'\n'"${extra_args}"
            fi

            # JV_VERSION only propagated to images that declare the ARG
            # (currently: base only -- jv is used by the init stage which
            # runs on brik-runner-base). Other images do not consume it
            # and would emit a non-blocking Docker warning if it were
            # passed unconditionally.
            jv_arg=""
            if [[ "$stack" == "base" ]]; then
                jv_arg=$'\n'"    JV_VERSION = \"${JV_VERSION}\""
            fi

            cat <<EOF
target "${target_name}" {
  dockerfile = "images/${stack}/Dockerfile"
  context    = "."
  args = {
    VERSION    = "${version}"
    YQ_VERSION = "${YQ_VERSION}"
    JQ_VERSION = "${JQ_VERSION}"${jv_arg}${formatted_extra}
  }
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ${tags}
}

EOF
        done
    done

    # Default group
    printf 'group "default" {\n'
    printf '  targets = [%s]\n' "$(IFS=,; echo "${ALL_TARGETS[*]}")"
    printf '}\n'

} > "$OUTPUT_FILE"

echo "Generated ${OUTPUT_FILE} with ${#ALL_TARGETS[@]} targets"
